import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useSelector } from 'react-redux'
import { selectBasketItems, selectBasketTotal } from '../redux/basketSlice'

import Header from '../components/Header'
import Button from '../components/Button'
import CheckoutProduct from '../components/CheckoutProduct'

import Currency from 'react-currency-formatter'
// import Stripe from "stripe";
// import getStripe from "../utils/get-stripejs";
// import { fetchPostJSON } from "../utils/api-helpers";

import { ChevronDownIcon } from '@heroicons/react/solid'

const Checkout = () => {
  const items = useSelector(selectBasketItems)
  const basketTotal = useSelector(selectBasketTotal)
  const router = useRouter()
  const [groupedItemsInBasket, setGroupedItemsInBasket] = useState(
    {} as { [key: string]: Product[] }
  )

  /**
   * O método reduce() executa uma função reducer (fornecida por você)
   * para cada elemento do array, resultando num único valor de retorno.
   *
   * A função reducer recebe até quatro parâmetros:
   * Acumulador (acc)
   * Valor Atual (cur)
   * Index Atual (idx)
   * Array original (src)
   *
   * O valor de retorno da sua função reducer é atribuída ao acumulador.
   * O acumulador, com seu valor atualizado, é repassado para cada iteração
   * subsequente pelo array, que por fim, se tornará o valor resultante, único, final.
   * --------------
   * Se haver o mesmo item no array, ele "se junta" com ele mesmo
   * E esse valor é adicionado ao acumulador -> results
   *
   * Sintaxe
   * array.reduce(callback( acumulador, valorAtual[, index[, array]] )[, valorInicial]))
   *
   * developer.mozilla.org
   */
  useEffect(() => {
    const groupedItems = items.reduce((results, item) => {
      ;(results[item._id] = results[item._id] || []).push(item)
      return results
    }, {} as { [key: string]: Product[] })

    setGroupedItemsInBasket(groupedItems)
  }, [items])

  return (
    <>
      <Head>
        <title>Apple / Bag</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="min-h-screen overflow-hidden bg-[#e7ecee]">
        <Header />
        <main className="max-w-5xl pb-24 mx-auto">
          <div className="px-5">
            <h1 className="my-4 text-3xl font-SFProText-600 lg:text-4xl">
              {items.length > 0 ? 'Review your bag.' : 'Your bag is empty.'}
            </h1>
            <p className="my-4">Free delivery and free returns.</p>
            {items.length === 0 && (
              <Button
                title="Continue Shopping"
                onClick={() => router.push('/')}
              />
            )}
          </div>
          {items.length > 0 && (
            <div className="mx-5 md:mx-8">
              {Object.entries(groupedItemsInBasket).map(([key, items]) => (
                <CheckoutProduct key={key} items={items} id={key} />
              ))}
              <div className="max-w-3xl mx-auto my-12 mt-6">
                <div className="divide-y divide-gray-300">
                  <div className="pb-4">
                    <div className="flex justify-between">
                      <p>Subtotal</p>
                      <p>
                        <Currency quantity={basketTotal} currency="USD" />
                      </p>
                    </div>
                    <div className="flex justify-between">
                      <p>Shipping</p>
                      <p>FREE</p>
                    </div>
                    <div className="flex justify-between">
                      <div className="flex flex-col gap-x-1 lg:flex-row">
                        Estimated tax for:{' '}
                        <p className="flex items-end text-blue-500 cursor-pointer hover:underline">
                          Enter zip code
                          <ChevronDownIcon className="w-6 h-6" />
                        </p>
                      </div>
                      <p>$ -</p>
                    </div>
                  </div>
                  <div className="flex justify-between pt-4 text-left font-SFProText-600">
                    <h4>Total</h4>
                    <h4>
                      <Currency quantity={basketTotal} currency="USD" />
                    </h4>
                  </div>
                </div>
                <div className="space-y-4 my-14">
                  <h4 className="text-xl font-SFProText-600">
                    How would you like to check out?
                  </h4>
                  <div className="flex flex-col gap-4 md:flex-row">
                    <div className="flex flex-col items-center flex-1 order-2 p-8 py-12 text-center bg-gray-200 rounded-xl">
                      <h4 className="flex flex-col mb-4 text-xl font-SFProText-600">
                        <span>Pay Monthly</span>
                        <span>with Apple Card</span>
                        <span>
                          $283.16/mo. at 0% APR<sup className="-top-1">◊</sup>
                        </span>
                      </h4>
                      <Button title="Check Out with Apple Card Monthly Installments" />
                      <p className="mt-2 max-w-[240px] text-[13px]">
                        $0.00 due today, which includes applicable full-price
                        items, down payments, shipping, and taxes.
                      </p>
                    </div>

                    <div className="flex flex-col items-center flex-1 p-8 py-12 space-y-8 bg-gray-200 rounded-xl md:order-2">
                      <h4 className="flex flex-col mb-4 text-xl font-SFProText-600">
                        Pay in full
                        <span>
                          <Currency quantity={basketTotal} currency="USD" />
                        </span>
                      </h4>

                      <Button
                        noIcon
                        // loading={loading}
                        title="Check Out"
                        width="w-full"
                        // onClick={createCheckoutSession}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </main>
      </div>
    </>
  )
}

export default Checkout
