import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Apple Store Online</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
    </div>
  )
}

export default Home
