import { Tab } from '@headlessui/react'
import type { GetServerSideProps, NextPage } from 'next'
import { Session } from 'next-auth'
import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Basket from '../components/Basket'
import Header from '../components/Header'
import Landing from '../components/Landing'
import Product from '../components/Product'
import { fetchCategories } from '../utils/fetchCategories'
import { fetchProducts } from '../utils/fetchProducts'

interface Props {
  categories: Category[]
  products: Product[]
  session: Session | null
}

// Backend Code
export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const categories = await fetchCategories()
  const products = await fetchProducts()
  const session = await getSession(context)

  return {
    props: {
      categories,
      products,
      session,
    },
  }
}

const style = {
  landingContainer: `relative h-[200vh] bg-[#E7ECEE]`,
  showProducts: {
    wrapper: `relative z-40 -mt-[100vh] min-h-screen bg-[#1B1B1B]`,
    container: `py-16 space-y-10`,
    newPromosTitle: `text-4xl font-medium tracking-wide text-center text-white md:text-5xl`,
    filterList: {
      container: `flex justify-center`,
      tabs: `whitespace-nowrap rounded-t-lg py-3 px-5 text-sm font-light outline-none md:py-4 md:px-6 md:text-base`,
      selected: `borderGradient bg-[#35383C] text-white`,
      notSelected: `border-b-2 border-[#35383C] text-[#747474]`,
      panels: `pt-10 pb-24 mx-auto max-w-fit sm:px-4`,
    },
  },

}

// Frontend code
const Home = ({ categories, products, session }: Props) => {
  const showProducts = (category: number) => {
    // filter products by category
    return products
      .filter((product) => product.category._ref === categories[category]._id)
      .map((product) => <Product product={product} key={product._id} />)
  }

  return (
    <>
      <Head>
        <title>Apple Store Online</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <Basket />

      <main className={style.landingContainer}>
        <Landing />
      </main>
      <section className={style.showProducts.wrapper}>
        <div className={style.showProducts.container}>
          <h1 className={style.showProducts.newPromosTitle}>
            New Promos
          </h1>

          <Tab.Group>
            <Tab.List className={style.showProducts.filterList.container}>
              {categories.map((category) => (
                <Tab
                  key={category._id}
                  id={category._id}
                  className={({ selected }) =>
                    `${style.showProducts.filterList.tabs} ${
                      selected
                        ? style.showProducts.filterList.selected
                        : style.showProducts.filterList.notSelected
                    }`
                  }
                >
                  {category.title}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className={style.showProducts.filterList.panels}>
              <Tab.Panel className="tabPanel">{showProducts(0)}</Tab.Panel>
              <Tab.Panel className="tabPanel">{showProducts(1)}</Tab.Panel>
              <Tab.Panel className="tabPanel">{showProducts(2)}</Tab.Panel>
              <Tab.Panel className="tabPanel">{showProducts(3)}</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </section>
    </>
  )
}

export default Home
