import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
// import { useSession } from "next-auth/react";
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { GetServerSideProps } from 'next'
import Currency from 'react-currency-formatter'
// import { fetchLineItems } from "../utils/fetchLineItems";

import Button from '../components/Button'

import {
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ShoppingCartIcon,
} from '@heroicons/react/outline'
// import { useMediaQuery } from "react-responsive";

interface Props {
  products: StripeProduct[]
}

const Success = () => {
  const router = useRouter()
  const { session_id } = router.query
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <>
      <Head>
        <title>Thank you! - Apple</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className="max-w-xl mx-auto">
        <Link href="/">
          <div className="relative w-8 h-16 ml-4 transition cursor-pointer lg:hidden">
            <Image
              src="/apple-logo-black.png"
              layout="fill"
              objectFit="contain"
              alt="apple/logo"
            />
          </div>
        </Link>
      </header>

      <main className="">
        <section className="order-2 max-w-xl pb-12 mx-auto lg:col-span-5 lg:mx-0 lg:max-w-none lg:pr-16 lg:pt-16 xl:pl-16 2xl:pl-44">
          <Link href="/">
            <div className="relative hidden w-12 h-24 transition cursor-pointer ml-14 lg:inline-flex">
              <Image
                src="/apple-logo-black.png"
                layout="fill"
                objectFit="contain"
                alt="apple/logo"
              />
            </div>
          </Link>

          <div className="flex my-8 ml-4 space-x-4 lg:ml-14 xl:ml-0">
            <div className="flex items-center justify-center text-center border-2 border-black rounded-full w-11 h-11 bottom-2">
              <CheckIcon className="w-8 h-8" />
            </div>
            <div>
              <p className="text-sm text-gray-600">
                Order #{session_id?.slice(-5)}
              </p>
              <h4 className="text-lg">
                Thank you{' '}
                {/* {session ? session.user?.name?.split(' ')[0] : 'Guest'} */}
              </h4>
            </div>
          </div>

          <div className="p-4 mx-4 border border-gray-300 divide-y divide-gray-300 rounded-md lg:ml-14">
            <div className="pb-3 space-y-2">
              <p>Your order is confirmed</p>
              <p className="text-sm text-gray-600">
                We’ve accepted your order, and we’re getting it ready. Come back
                to this page for updates on your shipment status.
              </p>
            </div>
            <div className="pt-3 text-sm">
              <p className="font-medium text-gray-600">
                Other tracking number:
              </p>
              <p>CNB21441622</p>
            </div>
          </div>

          <div className="p-4 mx-4 my-4 space-y-2 border border-gray-300 rounded-md lg:ml-14">
            <p>Order updates</p>
            <p className="text-sm text-gray-600">
              You’ll get shipping and delivery updates by email and text.
            </p>
          </div>

          <div className="flex flex-col items-center justify-between mx-4 text-sm lg:ml-14 lg:flex-row">
            <p className="hidden lg:inline">Need help? Contact us</p>
            {/* {mounted && (
              <Button
                title="Continue Shopping"
                onClick={() => router.push("/")}
                width={isTabletOrMobile ? "w-full" : undefined}
                padding="py-4"
              />
            )} */}
          </div>
        </section>
      </main>
    </>
  )
}

export default Success
